# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'tag to release'
        # Default value if no value is explicitly provided
        default: 'v0.0.6'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Prepare and publish the plugin to the Marketplace repository
  release:
    name: Publish Plugin
    runs-on: ubuntu-latest
    container: gradle:jdk8
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.input.tag_name }}

      # Publish the plugin to the Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin --stacktrace
